### ISSUE TITLE
Why is it that you use hex for `FakeCall`?

### ISSUE THREAD

**Issue by demberto** [ez8-co/unlocker#2]
Just why? What is the purpose of that function?

**Comment by orca-zhang** [comment]
I've forgot it. Maybe copyright of [Mr.Rewolf's article](http://blog.rewolf.pl/blog/?p=102) ?

**Comment by demberto** [comment]
Wow, that's interesting. I am too dumb to understand any of it, pretty clever people in this world. So, is it really possible to load a 32bit DLL in 64bit process and vice-versa after all?

Also, I am working on a GUI using this library. Do I need to have admin privileges for it? Since that would break drag and drop

**Comment by orca-zhang** [comment]
Yes, it's necessary to request admin privileges, there're some alternatives, like implicitly started by NT Service by `runas` command.

If you are interested in how to load a 32bit DLL in 64bit process, the library [yapi](https://github.com/ez8-co/yapi) is a good choice.

**Comment by demberto** [comment]
The issue isn't requesting admin privileges, its about drag and drop not working. Maybe my best bet is to make an additional hidden helper process which does the deletion while keeping UI process non-privileged. Then I can use IPC for reporting success/failure.

Btw, you should popularise yapi, its revolutionary tbh. Never have I seen a word about it anywhere.

Anyways, thanks for helping me out. I think you should mention it somewhere that admin privileges are required.

Edit: How about adding a `IsLocked` functionality, since unlocking files which aren't locked in the first place requires a considerable amount of time. Also is your library thread-safe?

**Comment by orca-zhang** [comment]
It's my pleasure that you like it. Thanks a ton.

Your `IsLocked` suggestion is quite good. And what's more, unlock the `mmf` file or not is depends on whether the file is occurred in file handles, cause that scan all handles for all processes is very very slow. I think it is necessary to provide function like `SlowUnlock` for the scenarios or it will fail to unlock now. 

: )

**Comment by orca-zhang** [comment]
And could you do me a favor that which sites can I popularize the libraries / repos? I'll publish some articles there.

**Comment by demberto** [comment]
> popularize

Answer similar questions on Stackoverflow, Quora, Reddit. Check out r/cpp subreddit. Your website ez8.co doesn't work, says TestPage184. For blogs, I suggest you to check out medium.com. I think it even pays authors. Keep repos regularly updated, I think you have now some ideas already for this one :)

> `IsLocked`

I think implementing it is as simple as asking for exclusive access to a file?

**Comment by demberto** [comment]
@orca-zhang Check out [EzUnlock](https://www.github.com/demberto/EzUnlock)
